cd %~dp0
set A0=%0
set A1=%1
set A2=%2
set A3=%3
set A4=%4
set A5=%5
set A6=%6
set A7=%7
set A8=%8
set A9=%9
shift
shift
shift
shift
shift
shift
shift
shift
shift
shift
set A10=%0
set A11=%1
set A12=%2
set A13=%3
set A14=%4
set A15=%5
set A16=%6
set A17=%7
set A18=%8
set A19=%9
shift
shift
shift
shift
shift
shift
shift
shift
shift
shift
set A20=%0
set A21=%1
set A22=%2
set A23=%3
set A24=%4
set A25=%5
set A26=%6
set A27=%7
set A28=%8
set A29=%9
shift
shift
shift
shift
shift
shift
shift
shift
shift
shift
set A30=%0
set A31=%1
set A32=%2
set A33=%3
set A34=%4
set A35=%5
set A36=%6
set A37=%7
set A38=%8
set A39=%9
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe %A1% %A2% %A3% %A4% %A5% %A6% %A7% %A8% %A9% %A10% %A11% %A12% %A13% %A14% %A15% %A16% %A17% %A18% %A19% %A20% %A21% %A22% %A23% %A24% %A25% %A26% %A27% %A28% %A29% %A30% %A31% %A32% %A33% %A34% %A35% %A36% %A37% %A38% %A39%
